var upperCamelCase = require('uppercamelcase');
var pluralize = require('pluralize');

function createBody(tableName) {
    return '' +
        'package ' + tableName + ';\n' +
        '\n' +
        'IMPORTS' +
        '\n' +
        '/**\n' +
        ' *		This class has been auto-generated by Modelizor.\n' +
        ' *		For license information, please LICENSE file at\n' +
        ' *		https://github.com/liminaab/modelizor\n' +
        ' */\n' +
        '@Entity\n' +
        '@Table(name=\"' + tableName + '\")\n' +
        '@Audited\n' +
        'public class ' + upperCamelCase(pluralize.singular(tableName)) + ' {\n' +
        '\n' +
        'VARIABLES' +
        '\n\n' +
        '	public ' + upperCamelCase(pluralize.singular(tableName)) + '() {\n' +
        '		// Auto-generated from Modelizor\n' +
        '	}\n' +
        '\n' +
        'PARAMS\n' +
        '}\n' +
        '';
}

exports.createBody = createBody;